"""empty message

Revision ID: 0bbec5b21290
Revises: 35087f2f8e08
Create Date: 2021-10-27 20:13:01.263413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bbec5b21290'
down_revision = '35087f2f8e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
