"""empty message

Revision ID: 24aa67cb1fde
Revises: 5e26f8c785d1
Create Date: 2021-10-31 12:57:22.858722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24aa67cb1fde'
down_revision = '5e26f8c785d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'viewed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'viewed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
