"""empty message

Revision ID: 3a0e96c0698b
Revises: 8b1e5ffffb33
Create Date: 2021-11-03 12:59:44.901439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a0e96c0698b'
down_revision = '8b1e5ffffb33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('recipient_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'recipient_id')
    # ### end Alembic commands ###
