"""empty message

Revision ID: 5e26f8c785d1
Revises: 0bbec5b21290
Create Date: 2021-10-31 12:53:59.997636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e26f8c785d1'
down_revision = '0bbec5b21290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('viewed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'viewed')
    # ### end Alembic commands ###
