"""empty message

Revision ID: 34db41782586
Revises: 
Create Date: 2021-10-13 15:21:19.845958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34db41782586'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supercategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('super_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['super_category_id'], ['supercategory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subcategory')
    op.drop_table('supercategory')
    # ### end Alembic commands ###
