"""empty message

Revision ID: b6cc9f315de8
Revises: c4d5652a6dce
Create Date: 2021-10-20 16:03:58.658049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6cc9f315de8'
down_revision = 'c4d5652a6dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('executor_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'executor_id')
    # ### end Alembic commands ###
