"""empty message

Revision ID: c4d5652a6dce
Revises: 5865c719dc6d
Create Date: 2021-10-19 15:27:41.856949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d5652a6dce'
down_revision = '5865c719dc6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'completed')
    # ### end Alembic commands ###
