"""empty message

Revision ID: 09ff062ecd40
Revises: d3dcf156b81a
Create Date: 2021-11-07 13:34:45.864543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ff062ecd40'
down_revision = 'd3dcf156b81a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('referral_link', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'user', ['referral_link'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'referral_link')
    # ### end Alembic commands ###
