"""empty message

Revision ID: 233801609c11
Revises: e7676da21d07
Create Date: 2021-10-04 17:03:30.297528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233801609c11'
down_revision = 'e7676da21d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification')
    # ### end Alembic commands ###
