"""empty message

Revision ID: 6044b9b97e7d
Revises: b044c0c38e08
Create Date: 2021-10-08 15:18:50.812269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6044b9b97e7d'
down_revision = 'b044c0c38e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('otp', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('otp_secret', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'otp_secret')
    op.drop_column('user', 'otp')
    # ### end Alembic commands ###
