"""empty message

Revision ID: b044c0c38e08
Revises: b8bd62fe7e62
Create Date: 2021-10-07 17:03:20.064435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b044c0c38e08'
down_revision = 'b8bd62fe7e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('git_id', sa.Integer(), nullable=False),
    sa.Column('git_username', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('git_id'),
    sa.UniqueConstraint('git_username'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github')
    # ### end Alembic commands ###
