"""empty message

Revision ID: b8bd62fe7e62
Revises: e7f745c0fcf1
Create Date: 2021-10-05 18:15:15.137510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8bd62fe7e62'
down_revision = 'e7f745c0fcf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
