"""empty message

Revision ID: e7676da21d07
Revises: aebf769b3868
Create Date: 2021-10-04 15:45:51.906411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7676da21d07'
down_revision = 'aebf769b3868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
