"""empty message

Revision ID: 9ba50bbaad60
Revises: 40213f0c4f78
Create Date: 2021-11-03 01:14:02.618920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba50bbaad60'
down_revision = '40213f0c4f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('client_name', sa.String(), nullable=False))
    op.alter_column('client', 'secret',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'client', ['client_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='unique')
    op.alter_column('client', 'secret',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('client', 'client_name')
    # ### end Alembic commands ###
